import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:temp/models/counter_cubit.dart';

/// This class is responsible for wrapping the UI in a button and iterating the amount of times it was clicked.
///
/// *Because this class was generated as a normal dart file, Parabeac will no longer touch this file.
/// This means that developers can create whatever they'd like here & Parabeac will reference this when needed.*
class CounterButton extends StatefulWidget {
  final Widget child;
  CounterButton({Key key, this.child}) : super(key: key);

  @override
  _CounterButtonState createState() => _CounterButtonState();
}

class _CounterButtonState extends State<CounterButton> {
  @override
  Widget build(BuildContext context) {
    /// *This was hand-written by Parabeac developers and was not generated by Parabeac-Core.*
    return GestureDetector(
      onTap: () {
        /// Here we increment the value in the cubit that the developer created to update the state.
        setState(() {
          context.read<CounterCubit>().increment();
        });
      },

      /// Here, we are leveraging the existing UI being sent to this widget.
      /// This is coming from my_app_screen.g.dart and can continue to be edited by the designer without impacting the logic written here.
      child: widget.child,
    );
  }
}
